export const SET_COUNTER = 'SET_COUNTER';
export const CLEAR_COUNTER = 'CLEAR_COUNTER';
export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';

export const PRESSED_HELLO_BUTTON = 'PRESSED_HELLO_BUTTON';